Python 3 fix: convert dict.keys() to a list before indexing it
In Python 2, dict.keys() returned a list but in Python 3 it returns
an opaque iterable type that doesn't directly support indexing.

Fixes this sort of error:

    Traceback (most recent call last):
      ..
      File "/home/sam/.local/lib/python3.6/site-packages/lastfmclient/package.py", line 9, in _call
        return self._client.call(http_method, method, auth, params)
      File "/home/sam/.local/lib/python3.6/site-packages/lastfmclient/client.py", line 76, in call
        return self._process_response_data(data)
      File "/home/sam/.local/lib/python3.6/site-packages/lastfmclient/client.py", line 131, in _process_response_data
        return data[keys[0]]
    TypeError: 'dict_keys' object does not support indexing